import { Colors, Styles } from '@/constants/theme';
import { Platform, ScaledSize, StyleSheet } from 'react-native';

export const getMatchDetailStyles = ({ width, height }: ScaledSize) => {
    const isTablet = width >= 600;
    // Calculate board size for two-column layout (board now gets ~70% of width)
    const availableWidth = width - (isTablet ? 64 : 40); // Subtract padding
    const leftColumnWidth = isTablet ? availableWidth * 0.7 : availableWidth;
    const boardSize = Math.min(leftColumnWidth - (isTablet ? 32 : 24), isTablet ? 500 : width - 40);

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: Colors.light.background,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: isTablet ? 32 : 20,
            paddingVertical: isTablet ? 20 : 16,
            backgroundColor: Colors.light.card,
            borderBottomWidth: 1,
            borderBottomColor: Colors.light.border,
        },
        backButton: {
            padding: 8,
            borderRadius: 12,
            backgroundColor: '#F3F4F6',
        },
        shareButton: {
            padding: 8,
            borderRadius: 12,
            backgroundColor: '#F3F4F6',
        },
        headerTitle: {
            fontSize: isTablet ? 22 : 18,
            fontWeight: '700',
            color: Colors.light.text,
        },
        content: {
            padding: isTablet ? 32 : 20,
            alignItems: 'center',
        },
        matchInfoCard: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            backgroundColor: Colors.light.card,
            paddingVertical: isTablet ? 16 : 12,
            paddingHorizontal: isTablet ? 24 : 20,
            borderRadius: 16,
            width: '100%',
            marginBottom: 20,
            borderWidth: 1,
            borderColor: Colors.light.border,
            ...Styles.shadow,
        },
        mainLayout: {
            flexDirection: isTablet ? 'row' : 'column',
            gap: isTablet ? 20 : 16,
            width: '100%',
            flex: 1,
        },
        leftColumn: {
            flex: isTablet ? 3 : 0,
            width: isTablet ? 'auto' : '100%',
            alignItems: 'center',
        },
        rightColumn: {
            flex: isTablet ? 1.2 : 0,
            width: isTablet ? 'auto' : '100%',
            minWidth: isTablet ? 200 : '100%',
        },
        playerInfo: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        avatarContainer: {
            width: isTablet ? 40 : 36,
            height: isTablet ? 40 : 36,
            borderRadius: isTablet ? 20 : 18,
            backgroundColor: '#F3F4F6',
            justifyContent: 'center',
            alignItems: 'center',
        },
        playerName: {
            fontSize: isTablet ? 16 : 14,
            fontWeight: '700',
            color: Colors.light.text,
        },
        playerElo: {
            fontSize: isTablet ? 14 : 12,
            color: Colors.light.icon,
            fontWeight: '600',
        },
        scoreContainer: {
            alignItems: 'center',
        },
        score: {
            fontSize: isTablet ? 24 : 20,
            fontWeight: '800',
            color: Colors.light.text,
            marginBottom: 4,
        },
        resultText: {
            fontSize: isTablet ? 16 : 14,
            fontWeight: '700',
            color: '#23b249',
        },
        boardContainer: {
            width: boardSize,
            height: boardSize,
            marginBottom: 20,
            borderRadius: 16,
            overflow: 'hidden',
            backgroundColor: '#EEE',
            ...Styles.shadow,
        },
        boardPlaceholder: {
            width: '100%',
            height: '100%',
        },
        gridOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            flexDirection: 'row',
            flexWrap: 'wrap',
        },
        square: {
            width: '12.5%',
            height: '12.5%',
            justifyContent: 'center',
            alignItems: 'center',
        },
        // Replay Controls
        replayControlsCard: {
            width: '100%',
            backgroundColor: Colors.light.card,
            borderRadius: 16,
            padding: isTablet ? 20 : 16,
            borderWidth: 1,
            borderColor: Colors.light.border,
            ...Styles.shadow,
            alignItems: 'center',
            gap: 16,
        },
        progressBarContainer: {
            width: '100%',
            height: 20,
            justifyContent: 'center',
        },
        progressBarTrack: {
            width: '100%',
            height: 4,
            backgroundColor: '#E5E7EB',
            borderRadius: 2,
        },
        progressBarFill: {
            height: '100%',
            backgroundColor: Colors.light.primary,
            borderRadius: 2,
        },
        progressBarThumb: {
            position: 'absolute',
            top: 2, // (20 - 16) / 2
            width: 16,
            height: 16,
            borderRadius: 8,
            backgroundColor: Colors.light.primary,
            borderWidth: 2,
            borderColor: '#FFFFFF',
            ...Styles.shadow,
        },
        moveCounterText: {
            fontSize: 14,
            color: Colors.light.textSecondary,
            fontWeight: '600',
        },
        mainControls: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 16,
        },
        controlButton: {
            width: 40,
            height: 40,
            borderRadius: 12,
            backgroundColor: '#FFFFFF',
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: Colors.light.border,
        },
        playButton: {
            width: 48,
            height: 48,
            borderRadius: 16,
            backgroundColor: Colors.light.primary,
            justifyContent: 'center',
            alignItems: 'center',
            ...Styles.shadow,
        },
        speedControls: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            marginTop: 4,
        },
        speedLabel: {
            fontSize: 12,
            color: Colors.light.textSecondary,
            marginRight: 4,
        },
        speedButton: {
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: Colors.light.border,
            backgroundColor: '#FFFFFF',
        },
        speedButtonActive: {
            backgroundColor: Colors.light.primary,
            borderColor: Colors.light.primary,
        },
        speedButtonText: {
            fontSize: 12,
            color: Colors.light.textSecondary,
            fontWeight: '600',
        },
        speedButtonTextActive: {
            color: '#FFFFFF',
        },
        moveListContainer: {
            width: '100%',
            maxHeight: isTablet ? 450 : 380,
            backgroundColor: Colors.light.card,
            borderRadius: 16,
            padding: isTablet ? 16 : 12,
            borderWidth: 1,
            borderColor: Colors.light.border,
            ...Styles.shadow,
        },
        moveListScroll: {
            flexGrow: 0,
            flexShrink: 1,
        },
        moveListTitle: {
            fontSize: isTablet ? 18 : 16,
            fontWeight: '700',
            color: Colors.light.text,
            marginBottom: 12,
        },
        moveGrid: {
            flexDirection: 'column',
            gap: 6,
        },
        moveListHeader: {
            flexDirection: 'row',
            marginBottom: 8,
            paddingBottom: 8,
            borderBottomWidth: 1,
            borderBottomColor: Colors.light.border,
        },
        moveListHeaderLabel: {
            flex: 1,
            fontSize: 12,
            fontWeight: '600',
            color: Colors.light.textSecondary,
            textAlign: 'center',
        },
        moveRow: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 8,
            gap: 8,
        },
        moveNumber: {
            width: 40,
            fontSize: 14,
            color: Colors.light.textSecondary,
            fontFamily: Platform.select({ ios: 'Courier New', android: 'monospace' }),
            textAlign: 'center',
        },
        moveItem: {
            flex: 1,
            paddingHorizontal: 10,
            paddingVertical: 8,
            borderRadius: 8,
            backgroundColor: '#F9FAFB',
            alignItems: 'center',
            justifyContent: 'center',
        },
        moveItemPlaceholder: {
            flex: 1,
        },
        activeMove: {
            backgroundColor: '#DBEAFE',
        },
        moveItemText: {
            fontSize: isTablet ? 14 : 13,
            color: '#4B5563',
            fontWeight: '600',
            fontFamily: Platform.select({ ios: 'Courier New', android: 'monospace' }),
        },
        activeMoveText: {
            color: '#1E40AF',
            fontWeight: '700',
        },
        gameStatsContainer: {
            marginTop: 16,
            width: '100%',
            backgroundColor: Colors.light.card,
            borderRadius: 16,
            padding: isTablet ? 16 : 12,
            borderWidth: 1,
            borderColor: Colors.light.border,
            ...Styles.shadow,
        },
        gameStatsTitle: {
            fontSize: isTablet ? 18 : 16,
            fontWeight: '700',
            color: Colors.light.text,
            marginBottom: 12,
        },
        statsGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 12,
        },
        statCard: {
            flex: 1,
            minWidth: '45%',
            backgroundColor: '#F9FAFB',
            borderRadius: 12,
            padding: 12,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        statIconContainer: {
            width: 40,
            height: 40,
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
        },
        statContent: {
            flex: 1,
        },
        statValue: {
            fontSize: 18,
            fontWeight: '700',
            color: Colors.light.text,
        },
        statLabel: {
            fontSize: 12,
            color: Colors.light.textSecondary,
            marginTop: 2,
        },
    });
};
